export const quotes = [
	'“idk … the oil holder broke and then it started smoking.. The and oil started spitting out of the engine” 06/15/2020',
	'“DAM you… My family didn’t even know that… Because in Florida and Pennsylvania they were normal… Or on drugs… Most likely on drugs” - 09/21/2020',
	'“So out of revenge i sent everyone that I knew where they were from what name they are” - 10/09/2020',
	'“Fuck you we didn’t do divison in Florida in 3rd. Ok we started counting coke in 2nd”. - 11/16/2020',
	'“I fell happiest in my skin when I am high” - 11/19/2020',
	"“Because you can't cyber bully innocents without typing like Putin” - 12/9/2020",
	'“Russia is still communist” - 1/4/2021',
	'“Ooooo 360… I only know 180… but sleeping 360” - 01/04/2021',
	'“If I were microwave I would bring in microwave popcorn” - 01/04/2021',
	'“All of my fucking smoke detectors went off for no fucking reason and my house has 3 floors and each floor has a couple smoke detectors” - 1/5/2021',
	'“I got there aftershokz head phones… It is hard to explain what they do but it delivers sound through your cheekbones” - 01/5/2021',
	'“I had to take out all of the batteries and turn off the house for then to stop” 01/05/2021',
	'“Want to know how I know because there is a thing called messaging later when you get the message and can’t respond it just stays there until you do or you read it… and it goes away once you respond” 01/05/2021',
	'“A communist is a dictator” - 1/5/2021',
	'“Fuck off” - Multiple',
	'“Hopefully then your empire will be my for 40 dollars and I dont feel like paying so I am going to guess that it goes back to you” 01/05/2021',
	'“What is hegel? Is it russian?” 01/05/2021',
	"“At the everglades people are incourged to shoot one type of snake because it doesn't belong there and it is destroying the ecosystem there” - 01/05/2021",
	'“@jonster5 right my child was pretty fucked up” - 01/05/2021',
	'“If you think about it, we are all brothers and sisters because we all came from that special animal” - 01/06/2021',
	'“Did you drug the dog? I druged my dog because my dog gets scared very easily like when the fire alarms went off” - 01/07/2021',
	'“how? SO A VOTE NOW” - 01/07/2021',
	'“I was playing with randoms they said I sucked when I was the goalie and defends every well and got 16 I guess knock outs” - 01/07/2021',
	'“I was riding on the people bring my fist over and bam knock out. It was fun I hit my small TV and a cup of water” - 01/07/2021',
	'“But I have gotten close I wish I had good teammates because they even said go crashlell get him and when missed the pass to the guy he said I sucked” - 01/07/2021',
	'“I swear my teacher is bi-polar” - 01/08/2021',
	"“Or when he said that we weren't Adults and something else because we didn't have our hands up when he was calling on random people” - 01/08/2021",
	'“What the hell is an ad-blocker?” -01/08/2021',
	'“I play Steam, I don’t need an ad-blocker” -01/08/2021',
	"“EVERYONE KEEPS SAYING THAT I HAVE A FUCKING VOICE CHANGER BUT I DON'T” - 01/08/2021",
	'“You should have just sucked it up like me” -01/08/2021',
	'“What type of wood do I have”  - 01/10/2021',
	'“I demand to know what wood I am” - 01/10/2021',
	'“I love british people, they’re so funny… they make so much sexual references” - 01/10/2021',
	'“That gum sucks… It is like a brick are you going to make a wall from that gum” - 1/11/2021',
	'“I not trying to be mean but that is a language I have never heard of it” - 01/11/2021',
	'“You know what is really fun about skipping one day of school like 2 Wednesday ago is that I have to keep making up work” - 01/11/2021',
	'“I had bad memories in Pennsylvania with killer clowns” - 01/11/2021',
	'“Omg I am so confused I was talking about killer clowns and was going to tell you my scary story that is true” - 01/11/2021',
	"“I got out of hand cuffs with my hands behind my back it took me like 20 minutes my sister didn't want to help me” - 01/11/2021",
	'“And when I use the word cop it is to be disrespectful and when I use officer that is me being respectful...So my dad is a cop” - 01/11/2021',
	`“PEOPLE SAID YOU CAN'T STORM AREA 51 AND WE DID. PEOPLE SAID YOU CAN'T STORM THE CAPITAL BUILDING AND WE SAID WE WILL NOT ONLY STORM IT WE WILL BE IN IT” - 01/11/2021`,
	'“What are you going to get hit” - 01/11/2021',
	'“i was rodding someone and then i stopped then they just walked off and i got the kill” -01/11/2021',
	'"ey they collect dead children in the attack" 01/12/2021',
	'“They do though. They collect dead children in the attic during child labor” - 01/12/2021',
	'“Really well facts show that people will vote for what ever is winning” -01/12/2021',
	'“Because lets see it is going be me and thats it” -01/12/2021',
	'“want to go zoom” - 01/12/2021',
	'“But do piston drives make you go zoom zoom” - 01/12/2021',
	'“I have a fragment of a dinosaur egg” -01/13/2021',
	'“How i bought it from a fossil store” - 01/13/2021',
	'“Stupid hacking NPCs” - 01/13/2021',
	'“Last time it stole one of these it did!” - 01/13/2021',
	'“Because Trump’s probably getting a cut of the money” - 01/13/2021',
	'“@Jonster5 I met a Birtish person” - 01/21/2021',
	'“One fogging Christmas eve Santa came to say I will for you in your sleep in your noddy they I said to him wait your not real and then he told me that he was a criminal dress like Santa.” - 1/21/2021',
	'“I fell on the ice and it hurts” - 01/25/2021',
	'“Go to hell but I do get 4 bars of wifi out there” - 01/25/2021',
	"“I remember this one kid from yesterday didn't how what the hell he was doing and he said leave me alone I getting groceries so I chased around the whole map while he was saying teammates help me this crazy person is after his teammates did come I just slice them and I killed the kid. I saw him again in a different map hiding behind a corner and saying don't kill me I will be your hostage and I will tell you where my teammates are so I just killed hik. Him*” - 01/26/2021",
	'“Space. Is out of this world. It is out of every world.” - 01/27/2021',
	'“I know where you live” - 01/28/2021',
	'“Maybe I will kill you in your sleep” - 01/28/2021',
	'“Go to hell” - Various',
	'“Lets blow up school or the place were there wifi from” - 01/28/2021',
	'“Hah, I haven’t said anything in an actual little while… except that long message thing” - 01/28/202',
	'“Fuck my car warranty is up and apparently I have to pay it again”  - 01/28/2021',
	'“How did they knks” - 01/28/2021',
	'“Yes I do [know when to walk away]! It’s when I don’t have anything to walk away with!” -01/28/2021',
	'“They called me again. I dont want a car warranty. I am missing the car part so warranty is useless. Maybe I can use the warranty on something else… Can a golf cart be classified as a car?” - 01/28/21',
	'“Shit lets get a warranty on that” -01/28/2021',
	'“And everyone is fucked want to know why. We dont live forever. This planet is fucked” - 01/28/2021',
	'“Ok so one drug dealer sells 50kilograms of drugs to another one but the dealer rips the guy off how many dead drug dealers are there” - 01/28/2021',
	'“I tried to go on the ice yesterday. In my backyard. But it broke” - 01/29/2021',
	'“Screw this I am going to be racist against orange people. Because so far I have only seen one orange person” - 02/04/2021',
	'“I love killing people with a knife” - 02/04/2021',
	'“I will stab you one day” - 02/04/2021',
	'“Even if I have to get a knife that is 6ft long” - 02/04/2021',
	'“Not nimble a aimble” - 02/04/2021',
	'“I meant ab” - 02/04/2021',
	'“Nerd you, I do” - 02/06/2021',
	'“My teacher is threatening a phone now with him throwing the phone into the snow” - 02/08/2021',
	'“If you want to talk like that then yeah. I know where most of you live” -02/08/2021',
	'“I am will kill you when you do get” -02/08/2021',
	'“Basterd” -02/08/2021',
	'“I’m from Florida… I can resist a gunshot” -02/11/2021',
	'“Either get right it or not say it at all” - 02/12/2021',
	'“We have to say 3 times and he will appear” -02/12/2021',
	'“Just killing and robbing and running from the cops” - 02/13/2021',
	'“I got eaten by a great white in it” - 02/13/2021',
	'“I went swimming in the ocean and I stole a boat and a shark came up so I tried to stab it and I couldnt so I jumped in and it ate me” - 02/13/2021',
	'“If I every play again I am shooting that shark” - 02/13/2021',
	'“Thank you much” - 02/13/2021',
	'“I really want this fish tank proof keyboard. Because we need to have our keyboards right next to our fish tanks and if we decide to destroy it and kill the robotic fish and destroy our computers we will only have broken computers and not a broken keyboard” -02/13/2021',
	'"i have 6 bastons" - 02/17/2021',
	'“no i destroyed one of my own because they blew up a falcon when i was trying to take it over” - 02/17/2021',
	'“Did the person who climb that long pole find at the top was climbing it was just a waste of time”  - 02/18/2021',
	'“People are praying to this guy in the mountains and he could stop covid but does he?” - 03/01/2021',
	`“You don't see people praying to scientists” - 03/01/2021`,
	'“I am understanding what you are saying now if you put the supremacy if mean that only they matter” - 03/01/2021',
	`“I am so tired and I don't want to fail my permit test. That is the only test i am concerned with even though I have a ela on that I don't care about. Ok I am going to take a practice quiz rn and I will honest about the score I get… So i got 8/10” - 03/02/2021`,
	`“I picked the only reasonable answer which was it effects your night vision. But the joke is you don't have night vision” - 03/02/2021`,
	'“So apparently I am tribe leader in ela and sasha is in my group so I am going to try to do something like survival where we vote someone out” - 03/04/2021',
	'“I hate when I get to many good cards” - 03/16/2021',
	'“Am I Alive?” - 03/16/2021',
	'“i crashed but i shall never burn” - 03/17/2021',
	'“He died. Now I am the main account” 03/17/2021',
	'“YOUR THE ALT”  - 03/17/2021',
	'“Crashlell was too weak” - 03/17/2021',
	'“I WANTS TO RISE AGAINST THE MAIN ACCOUNTS” - 03/17/2021',
	'“The fundraiser. They’re not raising funds it’s just a scam to get money” - 03/17/2021',
	'“Kill thr pig” - 03/17/2021',
	'“Ok let me see what he does first he moved his cruiser to where one of my quotes are” - 03/17/2021',
	'“COMSMOTEERS” - 03/17/2021',
	'“THE UNDERGROUND BELT.” 03/17/2021',
	'“The ship is unconscious” - 03/17/2021',
	'“I SAID THE LITTLE TANK THAT COULD” - 03/18/2021',
	'“I have to make brand new armor and such” - 03/18/2021',
	'“I’m saying such because my tank is such and so is my rifle” - 03/18/2021',
	'“I’m a sociopath” - 03/19/2021',
	'“All the orangutans died out” - 03/23/2021',
	'“*Gasp* that’s Among Us!” -03/23/2021',
	'“I’m saying everyone loses money when they die” - 03/23/2021',
	'“You know the best part of an addiction? It’s everything”  - 03/23/2021',
	'“Well if you want to fight a cunt then I do encourage you to fight yourself” - 03/24/2021',
	'“Narvin” - 03/24/2021',
	'“Has your parents seen the typical moids you use?” - 03/24/2021',
	'“Am I being arrested as well? Ooh, I am!” - 03/24/2021',
	'“NOW I KNOW WHY THEY SELL IT IN A 6 PACK. Because you need to drink 12 of them to get drunk” - 03/24/2021',
	'“It is already weird enough that Luke slept with prince laya” - 03/24/2021',
	'“So again he in my fucking tribe” - 03/25/2021',
	'“When He said I was thinking maybe a car will just hit him one day and they will never find the body because someone tied him to a bunch of weights and threw him over in the ocean or lake” - 03/25/2021',
	'“You had tk get an extension on your death timer” - 03/25/2021',
	'“Kill two stones with one bird” - 03/25/2021',
	'“What’s a pedo mean” - 03/25/2021',
	'“I think he is a pedophiler” - 03/25/2021',
];
